// GENERATED by scripts/gen-herdr-types.ts — do not edit.
// Source: `herdr api schema --json`, protocol 20.

export const HERDR_PROTOCOL = 20 as const;

export type HerdrAgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";

export type HerdrReadSource = "visible" | "recent" | "recent_unwrapped" | "detection";

export type HerdrReadFormat = "text" | "ansi";

/** One entry from `agent.list` -> result.agents[]. */
export interface HerdrAgentRaw {
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  cwd: string;
  foreground_cwd?: string;
  focused: boolean;
  name?: string | null;
  pane_id: string;
  revision: number;
  state_change_seq?: number;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  workspace_id: string;
}

/** One entry from `workspace.list` -> result.workspaces[]. */
export interface HerdrWorkspaceRaw {
  workspace_id: string;
  label?: string | null;
  number: number;
}

/** Payload of the `pane.agent_status_changed` subscription event. */
export interface HerdrStatusChanged {
  pane_id: string;
  workspace_id: string;
  agent_status: HerdrAgentStatus;
  agent?: string | null;
  display_agent?: string | null;
  title?: string | null;
  state_labels?: Record<string, string>;
}

/** `agent.read` -> result.read. The text is HERE, not on the envelope. */
export interface HerdrPaneReadResult {
  pane_id: string;
  workspace_id: string;
  tab_id: string;
  source: HerdrReadSource;
  format: HerdrReadFormat;
  text: string;
  revision: number;
  truncated: boolean;
}

/**
 * Full `agent.read` response envelope.
 *
 * Declared as the envelope rather than as the payload alone because the
 * defect this type exists to prevent was reading `result.text` — a field
 * that does not exist on either object. Typing the `request<>` call with
 * the envelope makes that a compile error instead of an empty pane.
 */
export interface HerdrPaneRead {
  type: "pane_read";
  read: HerdrPaneReadResult;
}

export interface HerdrRequest { id: string; method: string; params: object }
export type HerdrResponse =
  | { id: string; result: Record<string, unknown> }
  | { id: string; error: { message?: string; code?: string } };
export interface HerdrEvent { event: string; data: Record<string, unknown> }
