// GENERATED by scripts/gen-herdr-types.ts — do not edit.
// Source: `herdr api schema --json`, protocol 20.

export const HERDR_PROTOCOL = 20 as const;

export type HerdrAgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";

/**
 * The same set at RUNTIME, because a type cannot be checked at runtime and
 * `src/server/herdr/shape.ts` has to.
 *
 * paddock accepts a herdr newer than the one it was built against, so an ADDED
 * status is a real possibility — and `adapter.ts:toState` drops any row whose
 * status it does not render, which would make those agents vanish silently.
 * Emitted here rather than hand-written beside the check, so `make types` keeps
 * the two in step: a transcribed copy is exactly the silent drift decision 2
 * exists to prevent.
 */
export const HERDR_AGENT_STATUSES = ["idle", "working", "blocked", "done", "unknown"] as const;

export type HerdrReadSource = "visible" | "recent" | "recent_unwrapped" | "detection";

export type HerdrReadFormat = "text" | "ansi";

/**
 * The harness session herdr has associated with a pane, or null.
 *
 * `kind` is "id" for a session identifier and `value` is that id;
 * `agent` names the harness ("claude", "codex"). This is the key
 * `src/server/journal/` uses to find the harness's own log, and it is why
 * that feature needs no second herdr call: it rides on `agent.list`.
 */
export interface HerdrAgentSession {
  agent: string;
  kind: string;
  source: string;
  value: string;
}

/** One entry from `agent.list` -> result.agents[]. */
export interface HerdrAgentRaw {
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  agent_session?: HerdrAgentSession | null;
  cwd: string;
  foreground_cwd?: string;
  focused: boolean;
  name?: string | null;
  pane_id: string;
  revision: number;
  state_change_seq?: number;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  workspace_id: string;
}

/** One entry from `workspace.list` -> result.workspaces[]. */
export interface HerdrWorkspaceRaw {
  workspace_id: string;
  label?: string | null;
  number: number;
}

/** Payload of the `pane.agent_status_changed` subscription event. */
export interface HerdrStatusChanged {
  pane_id: string;
  workspace_id: string;
  agent_status: HerdrAgentStatus;
  agent?: string | null;
  display_agent?: string | null;
  title?: string | null;
  state_labels?: Record<string, string>;
}

/** `agent.read` -> result.read. The text is HERE, not on the envelope. */
export interface HerdrPaneReadResult {
  pane_id: string;
  workspace_id: string;
  tab_id: string;
  source: HerdrReadSource;
  format: HerdrReadFormat;
  text: string;
  revision: number;
  truncated: boolean;
}

/**
 * Full `agent.read` response envelope.
 *
 * Declared as the envelope rather than as the payload alone because the
 * defect this type exists to prevent was reading `result.text` — a field
 * that does not exist on either object. Typing the `request<>` call with
 * the envelope makes that a compile error instead of an empty pane.
 */
export interface HerdrPaneRead {
  type: "pane_read";
  read: HerdrPaneReadResult;
}

export interface HerdrRequest { id: string; method: string; params: object }
export type HerdrResponse =
  | { id: string; result: Record<string, unknown> }
  | { id: string; error: { message?: string; code?: string } };
export interface HerdrEvent { event: string; data: Record<string, unknown> }
