// GENERATED by scripts/gen-herdr-types.ts — do not edit.
// Source: `herdr api schema --json`, protocol 19.

export const HERDR_PROTOCOL = 19 as const;

export type HerdrAgentStatus = "idle" | "working" | "blocked" | "done" | "unknown";

/** One entry from `agent.list` -> result.agents[]. */
export interface HerdrAgentRaw {
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  cwd: string;
  foreground_cwd?: string;
  focused: boolean;
  name?: string | null;
  pane_id: string;
  revision: number;
  state_change_seq?: number;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  workspace_id: string;
}

/** One entry from `workspace.list` -> result.workspaces[]. */
export interface HerdrWorkspaceRaw {
  workspace_id: string;
  label?: string | null;
  number: number;
}

/** Payload of the `pane.agent_status_changed` subscription event. */
export interface HerdrStatusChanged {
  pane_id: string;
  workspace_id: string;
  agent_status: HerdrAgentStatus;
  agent?: string | null;
  display_agent?: string | null;
  title?: string | null;
  state_labels?: Record<string, string>;
}

export interface HerdrRequest { id: string; method: string; params: object }
export type HerdrResponse =
  | { id: string; result: Record<string, unknown> }
  | { id: string; error: { message?: string; code?: string } };
export interface HerdrEvent { event: string; data: Record<string, unknown> }
