/**
 * Generates `src/server/embedded.ts` — the map that lets one binary be the
 * whole product.
 *
 * Generated rather than committed because Vite content-hashes asset names, so
 * a committed manifest would silently drift from the bundle it claims to
 * describe. Writing an EMPTY map when `dist/` is absent is what keeps a fresh
 * clone's `make check` working before anything has been built.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const DIST = "dist";
const OUT = "src/server/embedded.ts";

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw e;   // a real read failure must not masquerade as "no assets"
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

const files = (await walk(DIST)).sort();
const lines: string[] = [
  "// GENERATED by scripts/gen-embedded.ts — do not edit, do not commit.",
  "// Regenerate with `make embed`. Empty when dist/ has not been built.",
];
const entries: string[] = [];
files.forEach((f, i) => {
  const url = "/" + relative(DIST, f).split("\\").join("/");
  lines.push(`import a${i} from "../../${f}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(url)}: a${i},`);
});
lines.push("", "export const EMBEDDED: Record<string, string> = {", ...entries, "};", "");
await writeFile(OUT, lines.join("\n"));
console.log(`gen-embedded: ${files.length} asset(s) -> ${OUT}`);
