// Generates src/shared/herdr-api.d.ts from the installed herdr's own schema.
// Run via `make types`. Never hand-edit the output.
import { ALLOW_DOWNGRADE_ENV, downgradeRefusal, parseCommittedProtocol } from "./protocol-guard";

// Both overridable so the downgrade guard can be tested without a second herdr
// install, the same way install.sh takes PADDOCK_CURL and PADDOCK_UNAME_S.
// Defaults are the real binary and the real committed path.
const HERDR_BIN = process.env.HERDR_BIN ?? "herdr";
const OUT = process.env.HERDR_TYPES_OUT ?? "src/shared/herdr-api.d.ts";

const proc = Bun.spawn([HERDR_BIN, "api", "schema", "--json"], { stdout: "pipe", stderr: "pipe" });
const raw = await new Response(proc.stdout).text();
if ((await proc.exited) !== 0) {
  throw new Error(`herdr api schema failed: ${await new Response(proc.stderr).text()}`);
}
const schema = JSON.parse(raw);

const protocol: number = schema.protocol;

// BEFORE reading the enums below, let alone writing them: on a downgrade those
// would be the older, smaller sets, and writing them is the whole harm. Exits
// rather than throwing so the operator gets the message and not a stack trace.
const existing = Bun.file(OUT);
const committed = (await existing.exists()) ? parseCommittedProtocol(await existing.text()) : null;
const refusal = downgradeRefusal(protocol, committed, Boolean(process.env[ALLOW_DOWNGRADE_ENV]));
if (refusal) {
  console.error(refusal);
  process.exit(1);
}

const states: string[] =
  schema.schemas.subscription_event.$defs.AgentStatus.enum;
const readSources: string[] =
  schema.schemas.success_response.$defs.ReadSource.enum;
const readFormats: string[] =
  schema.schemas.success_response.$defs.ReadFormat.enum;

const out = `// GENERATED by scripts/gen-herdr-types.ts — do not edit.
// Source: \`herdr api schema --json\`, protocol ${protocol}.

export const HERDR_PROTOCOL = ${protocol} as const;

export type HerdrAgentStatus = ${states.map((s) => `"${s}"`).join(" | ")};

/**
 * The same set at RUNTIME, because a type cannot be checked at runtime and
 * \`src/server/herdr/shape.ts\` has to.
 *
 * paddock accepts a herdr newer than the one it was built against, so an ADDED
 * status is a real possibility — and \`adapter.ts:toState\` drops any row whose
 * status it does not render, which would make those agents vanish silently.
 * Emitted here rather than hand-written beside the check, so \`make types\` keeps
 * the two in step: a transcribed copy is exactly the silent drift decision 2
 * exists to prevent.
 */
export const HERDR_AGENT_STATUSES = [${states.map((s) => `"${s}"`).join(", ")}] as const;

export type HerdrReadSource = ${readSources.map((s) => `"${s}"`).join(" | ")};

export type HerdrReadFormat = ${readFormats.map((s) => `"${s}"`).join(" | ")};

/**
 * The harness session herdr has associated with a pane, or null.
 *
 * \`kind\` is "id" for a session identifier and \`value\` is that id;
 * \`agent\` names the harness ("claude", "codex"). This is the key
 * \`src/server/journal/\` uses to find the harness's own log, and it is why
 * that feature needs no second herdr call: it rides on \`agent.list\`.
 */
export interface HerdrAgentSession {
  agent: string;
  kind: string;
  source: string;
  value: string;
}

/** One entry from \`agent.list\` -> result.agents[]. */
export interface HerdrAgentRaw {
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  agent_session?: HerdrAgentSession | null;
  cwd: string;
  foreground_cwd?: string;
  focused: boolean;
  name?: string | null;
  pane_id: string;
  revision: number;
  state_change_seq?: number;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  workspace_id: string;
}

/** One entry from \`workspace.list\` -> result.workspaces[]. */
export interface HerdrWorkspaceRaw {
  workspace_id: string;
  label?: string | null;
  number: number;
}

/** Payload of the \`pane.agent_status_changed\` subscription event. */
export interface HerdrStatusChanged {
  pane_id: string;
  workspace_id: string;
  agent_status: HerdrAgentStatus;
  agent?: string | null;
  display_agent?: string | null;
  title?: string | null;
  state_labels?: Record<string, string>;
}

/** \`agent.read\` -> result.read. The text is HERE, not on the envelope. */
export interface HerdrPaneReadResult {
  pane_id: string;
  workspace_id: string;
  tab_id: string;
  source: HerdrReadSource;
  format: HerdrReadFormat;
  text: string;
  revision: number;
  truncated: boolean;
}

/**
 * Full \`agent.read\` response envelope.
 *
 * Declared as the envelope rather than as the payload alone because the
 * defect this type exists to prevent was reading \`result.text\` — a field
 * that does not exist on either object. Typing the \`request<>\` call with
 * the envelope makes that a compile error instead of an empty pane.
 */
export interface HerdrPaneRead {
  type: "pane_read";
  read: HerdrPaneReadResult;
}

/** One entry from \`session.snapshot\` -> result.snapshot.workspaces[].
 *
 * Richer than \`HerdrWorkspaceRaw\`, which models only what \`workspace.list\`
 * needed for labelling. The rollup \`agent_status\`, \`pane_count\` and
 * \`tab_count\` are what let the Spaces screen show a space's shape without
 * walking its children.
 */
export interface HerdrWorkspaceInfo {
  workspace_id: string;
  label?: string | null;
  number: number;
  active_tab_id?: string | null;
  agent_status: HerdrAgentStatus;
  pane_count: number;
  tab_count: number;
  focused: boolean;
}

/** One entry from \`session.snapshot\` -> result.snapshot.tabs[].
 *
 * \`label\` is the tab's NUMBER as a string when the operator has never named
 * it, so "1" means unnamed rather than named "1". \`tree.ts\` is where that is
 * normalised; nothing else may assume it.
 */
export interface HerdrTabInfo {
  tab_id: string;
  workspace_id: string;
  label?: string | null;
  number: number;
  agent_status: HerdrAgentStatus;
  pane_count: number;
  focused: boolean;
}

/** One entry from \`session.snapshot\` -> result.snapshot.panes[].
 *
 * Carries NO \`name\`: only \`agent.list\` does, which is why
 * docs/gotchas.md forbids labelling from this. \`label\` is a DIFFERENT field
 * that \`agent.list\` does not read — see the design doc §14.3 before using it.
 */
export interface HerdrPaneInfo {
  pane_id: string;
  workspace_id: string;
  tab_id: string;
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  cwd: string;
  focused: boolean;
  label?: string | null;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  revision: number;
}

/** \`session.snapshot\` -> result.snapshot. The whole tree in one call. */
export interface HerdrSessionSnapshot {
  workspaces: HerdrWorkspaceInfo[];
  tabs: HerdrTabInfo[];
  panes: HerdrPaneInfo[];
  agents: HerdrAgentRaw[];
}

/** \`tab.create\` result. An ENVELOPE: the new tab AND its first pane.
 *
 * §9.1 originally said \`tab.create\` returns a bare \`TabInfo\` with no
 * \`pane_id\`, and prescribed re-reading the snapshot to find the new pane.
 * Measured false — the pane arrives here as \`root_pane\`. \`TabInfo\` the TYPE
 * genuinely has no pane id; reading a \`\$defs\` entry as the whole response is
 * the same mistake that produced the \`result.text\` bug.
 */
export interface HerdrTabCreated {
  type: "tab_created";
  tab: HerdrTabInfo;
  root_pane: HerdrPaneInfo;
}

/** \`workspace.create\` result. Same envelope shape, one level up. */
export interface HerdrWorkspaceCreated {
  type: "workspace_created";
  workspace: HerdrWorkspaceInfo;
  tab: HerdrTabInfo;
  root_pane: HerdrPaneInfo;
}

/** \`agent.start\` result. */
export interface HerdrAgentStarted {
  type: "agent_started";
  agent: HerdrAgentRaw;
}

/** \`server.agent_manifests\` result — the harnesses THIS machine has.
 *
 * The kind allowlist is derived from this at runtime and never hardcoded:
 * \`AgentStartParams.kind\` is a plain string in protocol 20, so the only
 * defensible allowlist is what is actually installed (§9.3).
 */
export interface HerdrAgentManifest { agent: string }
export interface HerdrAgentManifests {
  type: "agent_manifest_status";
  manifests: HerdrAgentManifest[];
}

export interface HerdrRequest { id: string; method: string; params: object }
export type HerdrResponse =
  | { id: string; result: Record<string, unknown> }
  | { id: string; error: { message?: string; code?: string } };
export interface HerdrEvent { event: string; data: Record<string, unknown> }
`;

await Bun.write(OUT, out);
console.log(`wrote ${OUT} (protocol ${protocol}, ${states.length} states)`);
