// Generates src/shared/herdr-api.d.ts from the installed herdr's own schema.
// Run via `make types`. Never hand-edit the output.
export {}; // Makes this a module so top-level await is allowed under tsc.

const proc = Bun.spawn(["herdr", "api", "schema", "--json"], { stdout: "pipe", stderr: "pipe" });
const raw = await new Response(proc.stdout).text();
if ((await proc.exited) !== 0) {
  throw new Error(`herdr api schema failed: ${await new Response(proc.stderr).text()}`);
}
const schema = JSON.parse(raw);

const protocol: number = schema.protocol;
const states: string[] =
  schema.schemas.subscription_event.$defs.AgentStatus.enum;
const readSources: string[] =
  schema.schemas.success_response.$defs.ReadSource.enum;
const readFormats: string[] =
  schema.schemas.success_response.$defs.ReadFormat.enum;

const out = `// GENERATED by scripts/gen-herdr-types.ts — do not edit.
// Source: \`herdr api schema --json\`, protocol ${protocol}.

export const HERDR_PROTOCOL = ${protocol} as const;

export type HerdrAgentStatus = ${states.map((s) => `"${s}"`).join(" | ")};

export type HerdrReadSource = ${readSources.map((s) => `"${s}"`).join(" | ")};

export type HerdrReadFormat = ${readFormats.map((s) => `"${s}"`).join(" | ")};

/** One entry from \`agent.list\` -> result.agents[]. */
export interface HerdrAgentRaw {
  agent?: string | null;
  agent_status: HerdrAgentStatus;
  cwd: string;
  foreground_cwd?: string;
  focused: boolean;
  name?: string | null;
  pane_id: string;
  revision: number;
  state_change_seq?: number;
  tab_id: string;
  terminal_id: string;
  terminal_title?: string | null;
  terminal_title_stripped?: string | null;
  workspace_id: string;
}

/** One entry from \`workspace.list\` -> result.workspaces[]. */
export interface HerdrWorkspaceRaw {
  workspace_id: string;
  label?: string | null;
  number: number;
}

/** Payload of the \`pane.agent_status_changed\` subscription event. */
export interface HerdrStatusChanged {
  pane_id: string;
  workspace_id: string;
  agent_status: HerdrAgentStatus;
  agent?: string | null;
  display_agent?: string | null;
  title?: string | null;
  state_labels?: Record<string, string>;
}

/** \`agent.read\` -> result.read. The text is HERE, not on the envelope. */
export interface HerdrPaneReadResult {
  pane_id: string;
  workspace_id: string;
  tab_id: string;
  source: HerdrReadSource;
  format: HerdrReadFormat;
  text: string;
  revision: number;
  truncated: boolean;
}

/**
 * Full \`agent.read\` response envelope.
 *
 * Declared as the envelope rather than as the payload alone because the
 * defect this type exists to prevent was reading \`result.text\` — a field
 * that does not exist on either object. Typing the \`request<>\` call with
 * the envelope makes that a compile error instead of an empty pane.
 */
export interface HerdrPaneRead {
  type: "pane_read";
  read: HerdrPaneReadResult;
}

export interface HerdrRequest { id: string; method: string; params: object }
export type HerdrResponse =
  | { id: string; result: Record<string, unknown> }
  | { id: string; error: { message?: string; code?: string } };
export interface HerdrEvent { event: string; data: Record<string, unknown> }
`;

await Bun.write("src/shared/herdr-api.d.ts", out);
console.log(`wrote src/shared/herdr-api.d.ts (protocol ${protocol}, ${states.length} states)`);
